"""Se corrige valor del campo pais codigo iso

Revision ID: b5b45f60d5a4
Revises: 
Create Date: 2023-09-30 14:12:10.703106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b45f60d5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ge_tpais', schema=None) as batch_op:
        batch_op.alter_column('pais_codigo_dian',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ge_tpais', schema=None) as batch_op:
        batch_op.alter_column('pais_codigo_dian',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
